#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "  _      _             _                     _    ____   _____ "
$L " | |    (_)           | |                   | |  / __ \ / ____|"
$L " | |     _  ___  _ __ | |__   ___  __ _ _ __| |_| |  | | (___  "
$L " | |    | |/ _ \| '_ \| '_ \ / _ \/ _` | '__| __| |  | |\___ \ "
$L " | |____| | (_) | | | | | | |  __/ (_| | |  | |_| |__| |____) |"
$L " |______|_|\___/|_| |_|_| |_|\___|\__,_|_|   \__|\____/|_____/ "
$L "Welcome to Android `getprop ro.build.version.release` / LionheartOS-`getprop ro.cm.version`";
